k_preferred_start = "preferred_start"
k_earliest_start = "earliest_start"
k_latest_finish = "latest_finish"
k_care_factor = "care_factor"
k_demand = "demand"
k_demand_profile = "demand_profile"
k_duration = "duration"
k_precedent = "precedent"
k_successor = "successor"
k_sequence = "sequence"
k_succeeding_delay = "succeeding_delay"

s_solver = "cp"
s_language = "minizinc"
